#!/bin/bash
javac ./components/Point.java
echo "Point.java ok"
javac ./components/Board.java 
echo "Board.java ok"
javac ./components/Pice.java
echo "Pice.java ok"
javac ./Checkers.java
echo "Checkers.java ok"
javac ./components/PiceType.java
echo "PiceType.java ok"